version: '3'
volumes:
  mysql-data: {}
  vscode-remote: {}
  vscode-server: {}
  jetbrains-data: {}
services:
  nginx:
    build:
      context: ./nginx
      args:
        API_DOMAIN: ${API_DOMAIN:?Missing API_DOMAIN}
        API_PORT: ${API_PORT:?Missing API_PORT}
        DASHBOARD_DOMAIN: ${DASHBOARD_DOMAIN:?Missing DASHBOARD_DOMAIN}
    ports:
      - ${DOCKER_WEB_PORT:?Missing DOCKER_WEB_PORT}:443
    volumes:
      - ../../:/zeppelin

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD?:Missing DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: zeppelin
      MYSQL_USER: zeppelin
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD?:Missing DOCKER_MYSQL_PASSWORD}
    ports:
      - ${DOCKER_MYSQL_PORT:?Missing DOCKER_MYSQL_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
#
#  backend:
#    image: node:16
#    user: "${UID:?Missing UID}:${GID:?Missing GID}"
#    working_dir: /zeppelin/backend
#    restart: always
#    depends_on:
#      - mysql
#    volumes:
#      - ./:/zeppelin
#    command: sh -c "npm run migrate-dev && npm run watch"
#
#  dashboard:
#    image: node:16
#    user: "${UID:?Missing UID}:${GID:?Missing GID}"
#    working_dir: /zeppelin/dashboard
#    restart: always
#    volumes:
#      - ./:/zeppelin
#    command: sh -c "npm run watch-build"

  devenv:
    build:
      context: ./devenv
      args:
        DOCKER_UID: ${DOCKER_UID:?Missing DOCKER_UID}
        DOCKER_GID: ${DOCKER_GID:?Missing DOCKER_GID}
        DOCKER_DEV_SSH_PASSWORD: ${DOCKER_DEV_SSH_PASSWORD:?Missing DOCKER_DEV_SSH_PASSWORD}
    ports:
      - "${DOCKER_DEV_SSH_PORT:?Missing DOCKER_DEV_SSH_PORT}:22"
    volumes:
      - ../../:/home/ubuntu/zeppelin
      - ~/.ssh:/home/ubuntu/.ssh
      - vscode-remote:/home/ubuntu/.vscode-remote
      - vscode-server:/home/ubuntu/.vscode-server
      - jetbrains-data:/home/ubuntu/.cache/JetBrains
